# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "linked_list"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
# assert_unordered = "0.3.5"
